### ISSUE TITLE
DOESN'T WORK WITH COLOMBIAN IPs

### ISSUE THREAD

**Issue by ErwinBustillo** [roryrjb/iplocation#20]
Hello I used this package in my express backend with node and I used mi local ip that it is from colombia bug the response json doesn't give any information about country name, code, latitud, longitude, etc. 
Can you fix this ?

**Comment by roryrjb** [comment]
No sorry, not directly anyway. This library relies on other third party providers having this data. There's already an issue (https://github.com/roryrjb/iplocation/issues/18) with the intent to include additional _fallback_ providers in the library itself, otherwise you can add other providers at runtime (see *Usage* for more details: https://github.com/roryrjb/iplocation#usage).
